create Day1
t-saba/Kintone_Dojo pull request #2
Opened 2020-06-12 01:47 UTC by t-saba

2020-06-12 01:59 UTC, miyass commented on Day1/3-02-var.html
> +<html lang="en">
いいね！！

2020-06-12 10:30 UTC, ahandsel requested changes

2020-06-12 10:30 UTC, ahandsel commented on Day1/3-02-var.html
> +  }
### 機能:
* コードは正しく機能します。わーい！
### フォーマット：
*エラーは重要な順になっています。*
87行: window.alertオブジェクトの後に";"(セミコロン)がたりない。
  * `window.alert( 'さわやかでしょ！');`
84、86、88行: “if” 文 の「)」と「{」の間にスペースが必要です。
  * リファレンス：[いくつかの条件：「else if」](https://ja.javascript.info/ifelse#ref-329)
  * If... else... 文 フォーマット:
    ```
      if (condition) {
        // code
      } else {
        // code
      }
    ```
82行: 不要な空行。
  * 行を削除してください。

2020-06-12 10:30 UTC, ahandsel commented
### 機能:
* コードは正しく機能します。わーい！
### フォーマット：
*エラーは重要な順になっています。*
87行: window.alertオブジェクトの後に";"(セミコロン)がたりない。
  * `window.alert( 'さわやかでしょ！');`
84、86、88行: “if” 文 の「)」と「{」の間にスペースが必要です。
  * リファレンス：[いくつかの条件：「else if」](https://ja.javascript.info/ifelse#ref-329)
  * If... else... 文 フォーマット:
    ```
      if (condition) {
        // code
      } else {
        // code
      }
    ```
82行: 不要な空行。
  * 行を削除してください。

2020-06-15 04:54 UTC, ahandsel commented
変更していただきありがとうございます。コードは完璧なのでプルリクエストをマージします！

Thank you for making the changes. Your code looks perfect!
Will Merge the Pull Request!

2020-06-15 04:55 UTC, merged